CRITICAL - 2025-05-13 11:03:22 --> PHPUnit\TextUI\RuntimeException: Class "App\Base\BaseTestCase" not found
[Method: GET, Route: /]
in VENDORPATH/phpunit/phpunit/src/TextUI/Command.php on line 101.
 1 VENDORPATH/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
 2 VENDORPATH/bin/phpunit(120): include('/var/www/webs/api_Ionic/vendor/phpunit/phpunit/phpunit')
CRITICAL - 2025-05-13 11:03:22 --> [Caused by] Error: Class "App\Base\BaseTestCase" not found
in ROOTPATH/tests/app/Controllers/ApiControllerTest.php on line 14.
 1 VENDORPATH/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
 2 VENDORPATH/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
 3 VENDORPATH/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php(43): PHPUnit\Util\FileLoader::checkAndLoad()
 4 VENDORPATH/phpunit/phpunit/src/Runner/BaseTestRunner.php(146): PHPUnit\Runner\StandardTestSuiteLoader->load()
 5 VENDORPATH/phpunit/phpunit/src/Runner/BaseTestRunner.php(112): PHPUnit\Runner\BaseTestRunner->loadSuiteClass()
 6 VENDORPATH/phpunit/phpunit/src/TextUI/Command.php(123): PHPUnit\Runner\BaseTestRunner->getTest()
 7 VENDORPATH/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run()
 8 VENDORPATH/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
 9 VENDORPATH/bin/phpunit(120): include('/var/www/webs/api_Ionic/vendor/phpunit/phpunit/phpunit')
ERROR - 2025-05-13 11:04:10 --> Error connecting to the database: Error: Class "SQLite3" not found in /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php:112
Stack trace:
#0 /var/www/webs/api_Ionic/system/Database/BaseConnection.php(421): CodeIgniter\Database\SQLite3\Connection->connect()
#1 /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php(74): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(83): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(59): App\Base\BaseTestCase->loadDependencies()
#4 /var/www/webs/api_Ionic/system/Test/CIUnitTestCase.php(251): App\Base\BaseTestCase->setUpDatabase()
#5 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(1216): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestResult.php(729): PHPUnit\Framework\TestCase->runBare()
#7 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(973): PHPUnit\Framework\TestResult->run()
#8 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestSuite.php(685): PHPUnit\Framework\TestCase->run()
#9 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run()
#10 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(146): PHPUnit\TextUI\TestRunner->run()
#11 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run()
#12 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#13 /var/www/webs/api_Ionic/vendor/bin/phpunit(120): include('...')
#14 {main}
ERROR - 2025-05-13 11:04:10 --> Error connecting to the database: Error: Class "SQLite3" not found in /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php:112
Stack trace:
#0 /var/www/webs/api_Ionic/system/Database/BaseConnection.php(421): CodeIgniter\Database\SQLite3\Connection->connect()
#1 /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php(74): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(83): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(59): App\Base\BaseTestCase->loadDependencies()
#4 /var/www/webs/api_Ionic/system/Test/CIUnitTestCase.php(251): App\Base\BaseTestCase->setUpDatabase()
#5 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(1216): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestResult.php(729): PHPUnit\Framework\TestCase->runBare()
#7 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(973): PHPUnit\Framework\TestResult->run()
#8 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestSuite.php(685): PHPUnit\Framework\TestCase->run()
#9 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run()
#10 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(146): PHPUnit\TextUI\TestRunner->run()
#11 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run()
#12 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#13 /var/www/webs/api_Ionic/vendor/bin/phpunit(120): include('...')
#14 {main}
ERROR - 2025-05-13 11:04:10 --> Error connecting to the database: Error: Class "SQLite3" not found in /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php:112
Stack trace:
#0 /var/www/webs/api_Ionic/system/Database/BaseConnection.php(421): CodeIgniter\Database\SQLite3\Connection->connect()
#1 /var/www/webs/api_Ionic/system/Database/SQLite3/Connection.php(74): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(83): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 /var/www/webs/api_Ionic/system/Test/DatabaseTestTrait.php(59): App\Base\BaseTestCase->loadDependencies()
#4 /var/www/webs/api_Ionic/system/Test/CIUnitTestCase.php(251): App\Base\BaseTestCase->setUpDatabase()
#5 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(1216): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestResult.php(729): PHPUnit\Framework\TestCase->runBare()
#7 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestCase.php(973): PHPUnit\Framework\TestResult->run()
#8 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/Framework/TestSuite.php(685): PHPUnit\Framework\TestCase->run()
#9 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run()
#10 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(146): PHPUnit\TextUI\TestRunner->run()
#11 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run()
#12 /var/www/webs/api_Ionic/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#13 /var/www/webs/api_Ionic/vendor/bin/phpunit(120): include('...')
#14 {main}
ERROR - 2025-05-13 11:32:52 --> Error al obtener el juego con ID 2: Expectation failed for method name is "find" when invoked zero or more times
Parameter 0 for invocation CodeIgniter\BaseModel::find(2) does not match expected value.
Failed asserting that 2 matches expected 1.
ERROR - 2025-05-13 11:33:07 --> Error al obtener el juego con ID 2: Expectation failed for method name is "find" when invoked zero or more times
Parameter 0 for invocation CodeIgniter\BaseModel::find(2) does not match expected value.
Failed asserting that 2 matches expected 1.
ERROR - 2025-05-13 11:43:18 --> Error al obtener el juego con ID 9999: Expectation failed for method name is "find" when invoked zero or more times
Parameter 0 for invocation CodeIgniter\BaseModel::find(9999) does not match expected value.
Failed asserting that 9999 matches expected 1.
ERROR - 2025-05-13 11:46:42 --> Error al obtener el juego con ID 9999: Expectation failed for method name is "find" when invoked zero or more times
Parameter 0 for invocation CodeIgniter\BaseModel::find(9999) does not match expected value.
Failed asserting that 9999 matches expected 1.
